### ISSUE TITLE
DAIS Identifier is Missing: Natarajan Sriraam

### ISSUE THREAD

**Issue by obscrivn** [cns-iu/phi#16]
Natarajan Sriraam - None of records with dais correspond to WOS gold standard files from Ries - https://iu.app.box.com/folder/39176046906. Given that there are only 541 records of Natarajan ‘S’ and ‘Sriraam’  - I compared all 24 WOS gold records with 541 WOS extracts using ‘Sriraam’ - all 24 records are there (except one additional that is not clear - no affiliation in the paper (“machine Learning for Personalized Medicine).

I will extract the above mentioned 24 records. Will it be ok?

**Comment by bherr2** [comment]
Yeah, its inevitable that we'll have to do more than just do a list of DAIS, so that's ok. We just need to document it and ideally have it part of a reproduceable workflow.

**Comment by bherr2** [comment]
Closing. We'll not worry about DAIS right now.
