### ISSUE TITLE
Data is messy

### ISSUE THREAD

**Issue by bherr2** [cns-iu/phi#7]
The current publication data is very messy. 

* [ ] Normalize authors
* [ ] Fix publication years
* [ ] Get ISSN/ISBN numbers for each Journal
* [ ] Normalize publications fully
* [ ] Update publications with latest / cleanest version

**Comment by katyb** [comment]
Or simply acquire new data from a high quality source.
k


--
Katy Borner
Victor H. Yngve Distinguished Professor of Engineering and Information Science
Director, CI for Network Science Center, http://cns.iu.edu
Curator, Mapping Science exhibit, http://scimaps.org

ISE and ILS, School of Informatics, Computing, and Engineering, Indiana University
Luddy Hall 4018, 700 N. Woodlawn Ave, Bloomington, IN 47408, USA
Phone: (812) 855-3256  Fax: -6166
